name: psalm

on:
  push:
    branches:
      - 'gh-pages'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  psalm:
    name: Psalm Static Analysis on PHP ${{ matrix.php-version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.4'
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml
          tools: composer:v2
          coverage: none

      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --dev

      - name: Run Psalm
        run: vendor/bin/psalm --config=psalm.xml.dist --show-info=true
